message = {
    "en":{
        "0_ADD_SUCCESSFUL":"Added successfully.",
        "0_MODIFY_SUCCESSFUL":"Modified successfully.",
        "0_DELETE_SUCCESSFUL":"Deleted successfully.",
        "401_MAXIMUM_THREE":"The Maximum number of portfolio is three.",
        "402_NOT_EXIST":"This portfolio does not exist.",
        "403_LOGIN":"Please login.",
        "405_INVAID_CODE":"Invaid code.",
        "406_NUMBER_COINS": "The number of coins has to be between 1 and 10.",
        "407_DUPLICATION_COIN": "The portfolio have the duplication of coin.",
        "408_NOT_VIEW":"You do not have permission to view this page.",
        "409_NOT_DELETE":"You do not have permission to delete this portfolio.",
        "410_ACCOUNT_ACCESS":"This account is not activated and has no access rights.",
        "411_COIN_NOT_EXIST":"This coin does not exist.",
        "412_NUMBER_TRIALS_500":"Number of trials cannot be greater than 500.",
        "415_WEIGHT_EXCEED":"Coin weight cannot exceed 100%.",
        "416_REQ_FREQUENT":"Your operation is too frequent, Please try again later.",
        "417_WEIGHT_NOT_LESS_0":"The weight should not be less than 0.",
        "431_ACCOUNT_ACCESS":"This account has no access rights.",
        "500_SERVER_ERROR":"Server error.",
        '% Losses': '% Losses',
        'Cumulative Return': 'Cumulative Return',
        '% Volatility': '% Volatility',
        'Value At Risk (Normal)': 'Value At Risk (Normal)',
        'Average Loss': 'Average Loss',
        '% Gains': '% Gains',
        'Sortino': 'Sortino',
        'Best Return': 'Best Return',
        'Annualized Return': 'Annualized Return',
        'VaR Adj': 'VaR Adj',
        'Number of Periods': 'Number of Periods',
        'Average Daily Return': 'Average Daily Return',
        'Worst Period': 'Worst Period',
        'Average Gain': 'Average Gain',
        'Sharpe Ratio': 'Sharpe Ratio',
        'Max Drawdown': 'Max Drawdown',
        'Annualized Volatility': 'Annualized Volatility'
    },
    "ko_KR":{
        "0_ADD_SUCCESSFUL":"성공적으로 추가됨.",
        "0_MODIFY_SUCCESSFUL":"성공적으로 수정됨.",
        "0_DELETE_SUCCESSFUL":"성공적으로 삭제됨.",
        "401_MAXIMUM_THREE":"포트폴리오 최대치는 3입니다.",
        "402_NOT_EXIST":"이번 포트폴리오는 존재하지 않음.",
        "403_LOGIN":"좀 로그인.",
        
        "405_INVAID_CODE":"무효 코드.",
        "406_NUMBER_COINS":"코인 수는 1부터 10사이여야 합니다.",
        "407_DUPLICATION_COIN":"포트폴리오는 코인 복사본이 있습니다.",
        "408_NOT_VIEW":"당신은 본 페이지를 볼 권한이 없습니다.",
        "409_NOT_DELETE":"당신은 본 페이지를 삭제할 권한이 없습니다.",
        "410_ACCOUNT_ACCESS":"본 계정은 활성화되지 않아 접근 권한이 없습니다.",
        "411_COIN_NOT_EXIST":"해당 코인은 존재하지 않음.",
        "412_NUMBER_TRIALS_500":"시도 횟수는 500을 넘어설 수 없습니다.",
        "415_WEIGHT_EXCEED":"코인 무게는 100%를 초과할 수 없습니다.",
        "416_REQ_FREQUENT":"방문한 횟수가 너무 빈번하다.",
        "417_WEIGHT_NOT_LESS_0":"무게는 0이하여서는 안 됨.",
        "431_ACCOUNT_ACCESS":"본 계정은 접근 권한이 없습니다.",
        "500_SERVER_ERROR":"서버 오류.",
        '% Losses': '% 손실',
        'Cumulative Return': '누적 수익률',
        '% Volatility': '% 가변성',
        'Value At Risk (Normal)': '위험 가치 (정상)',
        'Average Loss': '평균 손실',
        '% Gains': '% 수익',
        'Sortino': '성',
        'Best Return': '최대 수익률',
        'Annualized Return': '연평균 수익률',
        'VaR Adj': 'VAR 조정',
        'Number of Periods': '기간 수',
        'Average Daily Return': '일간 평균 수익률',
        'Worst Period': '최악의 시기',
        'Average Gain': '평균 수익',
        'Sharpe Ratio': '샤프지수',
        'Max Drawdown': '최대 축소',
        'Annualized Volatility': '연간 가변성'
    }
    
}
